import type { ClosedSession, SessionRow } from '../../src/contract/types/reads-types.ts'

/** What `GET /api/workspaces/ses-workspace/sessions` carries in `sessions` for the relay's seeded test database. */
export const sessions: SessionRow[] = [
	{
		id: 'ses-claude-5m',
		status: 'idle',
		title: 'Plan the migration',
		model: 'ses-model-opus',
		permission_mode: 'plan',
		claude_effort_level: 'high',
		fast_mode: 1,
		agent_type: 'claude',
		context_used_percent: 42.5,
		unread_count: 1,
		created_at: '2026-09-01 08:00:00',
		updated_at: '2026-09-01 08:30:00',
		last_user_message_at: '2026-09-01 08:20:00',
		prompt_cache_ttl_ms: 300000,
		turn_started_at: '2026-09-01 08:20:00',
		background_tasks: []
	},
	{
		id: 'ses-codex-ultra',
		status: 'working',
		title: 'Port the parser',
		model: 'ses-model-codex',
		permission_mode: 'default',
		claude_effort_level: 'ultracode',
		fast_mode: 0,
		agent_type: 'codex',
		context_used_percent: 7.25,
		unread_count: 0,
		created_at: '2026-09-01 09:00:00',
		updated_at: '2026-09-01 09:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: null,
		turn_started_at: null,
		background_tasks: []
	},
	{
		id: 'ses-codex-no-effort',
		status: 'idle',
		title: 'Tidy the config',
		model: null,
		permission_mode: 'default',
		claude_effort_level: null,
		fast_mode: 0,
		agent_type: 'codex',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-01 10:00:00',
		updated_at: '2026-09-01 10:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: null,
		turn_started_at: null,
		background_tasks: []
	},
	{
		id: 'ses-cursor',
		status: 'idle',
		title: 'Sketch the panel',
		model: 'ses-model-cursor',
		permission_mode: 'default',
		claude_effort_level: 'xhigh',
		fast_mode: 0,
		agent_type: 'cursor',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-01 11:00:00',
		updated_at: '2026-09-01 11:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: null,
		turn_started_at: null,
		background_tasks: []
	},
	{
		id: 'ses-anthropic-1h',
		status: 'idle',
		title: 'Review the diff',
		model: null,
		permission_mode: 'default',
		claude_effort_level: 'max',
		fast_mode: 0,
		agent_type: 'anthropic',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-02 08:00:00',
		updated_at: '2026-09-02 08:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: 3600000,
		turn_started_at: null,
		background_tasks: []
	},
	{
		id: 'ses-claude-mixed',
		status: 'idle',
		title: 'Mixed cache',
		model: null,
		permission_mode: 'default',
		claude_effort_level: 'low',
		fast_mode: 0,
		agent_type: 'claude',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-02 09:00:00',
		updated_at: '2026-09-02 09:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: 300000,
		turn_started_at: null,
		background_tasks: []
	},
	{
		id: 'ses-claude-zero',
		status: 'idle',
		title: 'No cache write',
		model: null,
		permission_mode: 'default',
		claude_effort_level: 'none',
		fast_mode: 0,
		agent_type: 'claude',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-02 10:00:00',
		updated_at: '2026-09-02 10:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: null,
		turn_started_at: null,
		background_tasks: []
	},
	{
		id: 'ses-iso-created',
		status: 'idle',
		title: 'Clock format',
		model: null,
		permission_mode: 'default',
		claude_effort_level: 'max',
		fast_mode: 0,
		agent_type: 'claude',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-02T07:00:00.000Z',
		updated_at: '2026-09-02T07:30:00.000Z',
		last_user_message_at: '2026-09-02T07:20:00.000Z',
		prompt_cache_ttl_ms: null,
		turn_started_at: null,
		background_tasks: []
	},
	{
		id: 'ses-running-turn',
		status: 'working',
		title: 'Running turn',
		model: null,
		permission_mode: 'default',
		claude_effort_level: 'medium',
		fast_mode: 0,
		agent_type: 'claude',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-03 08:00:00',
		updated_at: '2026-09-03 08:00:00',
		last_user_message_at: '2026-09-03 10:05:00',
		prompt_cache_ttl_ms: null,
		turn_started_at: '2026-09-03 10:00:00',
		background_tasks: []
	},
	{
		id: 'ses-queued',
		status: 'idle',
		title: 'Queued behind',
		model: null,
		permission_mode: 'default',
		claude_effort_level: 'high',
		fast_mode: 0,
		agent_type: 'claude',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-03 09:00:00',
		updated_at: '2026-09-03 09:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: null,
		turn_started_at: '2026-09-03 09:10:00',
		background_tasks: []
	},
	{
		id: 'ses-legacy-queue',
		status: 'idle',
		title: 'Before turn ids',
		model: null,
		permission_mode: 'default',
		claude_effort_level: 'low',
		fast_mode: 0,
		agent_type: 'claude',
		context_used_percent: null,
		unread_count: 0,
		created_at: '2026-09-03 10:00:00',
		updated_at: '2026-09-03 10:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: null,
		turn_started_at: '2026-08-20 12:30:00',
		background_tasks: []
	},
	{
		id: 'ses-legacy-open',
		status: null,
		title: null,
		model: null,
		permission_mode: null,
		claude_effort_level: null,
		fast_mode: null,
		agent_type: null,
		context_used_percent: null,
		unread_count: null,
		created_at: '2026-09-04 08:00:00',
		updated_at: '2026-09-04 08:00:00',
		last_user_message_at: null,
		prompt_cache_ttl_ms: null,
		turn_started_at: null,
		background_tasks: []
	}
]

/** What `GET /api/workspaces/ses-workspace/sessions/closed` carries in `sessions` for the same database. */
export const closedSessions: ClosedSession[] = [
	{
		id: 'ses-closed-space',
		title: 'Closed, space format',
		model: 'ses-model-opus',
		agent_type: 'claude',
		created_at: '2026-09-05 09:00:00',
		updated_at: '2026-09-10 13:00:00'
	},
	{
		id: 'ses-closed-iso',
		title: 'Closed, ISO format',
		model: 'ses-model-codex',
		agent_type: 'codex',
		created_at: '2026-09-05 08:00:00',
		updated_at: '2026-09-10T12:00:00.000Z'
	},
	{
		id: 'ses-closed-tie-c',
		title: 'Tie, created last',
		model: null,
		agent_type: 'claude',
		created_at: '2026-09-05 11:00:00',
		updated_at: '2026-09-09 10:00:00'
	},
	{
		id: 'ses-closed-tie-a',
		title: 'Tie, same creation',
		model: null,
		agent_type: 'claude',
		created_at: '2026-09-05 10:00:00',
		updated_at: '2026-09-09 10:00:00'
	},
	{
		id: 'ses-closed-tie-b',
		title: null,
		model: null,
		agent_type: 'cursor',
		created_at: '2026-09-05 10:00:00',
		updated_at: '2026-09-09 10:00:00'
	},
	{
		id: 'ses-closed-old',
		title: 'Closed long ago',
		model: null,
		agent_type: null,
		created_at: '2026-08-01 08:00:00',
		updated_at: '2026-08-01 09:00:00'
	}
]
